### ISSUE TITLE
Global score not update when use other browsers instead of chrome

### ISSUE THREAD

**Issue by tomhero** [tomhero/flip-card-games-web#1]
Device:
-  iPad Mini/ Xiaomi 9T Pro
-  iOS 13/Android 10
- Safari/Chrome mobile

Symptom:
- The global score can not be fetched
- Can't update the high score to global scoreboard

**Comment by tomhero** [comment]
Because of netlify, so i wont fix it.

```js
[object Error]: {config: Object, description: "Network Error", isAxiosError: true, message: "Network Error", request: XMLHttpRequest...}

config: Object
description: "Network Error"
isAxiosError: true
message: "Network Error"

request: XMLHttpRequest
response: undefined
stack: "Error: Network Error at E.prototype.stop (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:7:88666) at Anonymous function (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/app.36ee729b.js:1:12090) at u (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:7:84669) at Anonymous function (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:7:86007) at t[e] (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:7:85086) at r (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:1:5042) at s (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:1:5291) at Anonymous function (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:14:10469) at r (https://5e0ca1248f8744a0d9006a55--objective-shaw-cad335.netlify.com/js/chunk-vendors.f8ac7132.js:7:100900)"

toJSON: function (){return{message:this.message,name:this.name,description:this.description,number:this.number,fileName:this.fileName,lineNumber:this.lineNumber,columnNumber:this.columnNumber,stack:this.stack,config:this.config,code:this.code}}

__proto__: Error
```
